default_install_hook_types:
  - pre-commit
  - commit-msg
  - post-checkout
  - post-merge
  - post-rewrite

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: detect-private-key

  - repo: https://github.com/ComPWA/taplo-pre-commit
    rev: v0.9.3
    hooks:
      - id: taplo-format

  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.7
    hooks:
      - id: actionlint

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.2.1
    hooks:
      - id: commitizen

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.5.29
    hooks:
      - id: uv-lock
